[package]
name = "datafusion_nats"
version = "0.1.0"
edition = "2024"

[dependencies]
datafusion = "48.0.1"
async-nats = "0.42.0"
tokio = { version = "1", features = ["full"] }
anyhow = "1.0"
thiserror = "2.0"
async-trait = "0.1"
futures = "0.3"
